
export default [
    {
        kid : 1,
        image : "./images/itemone.jpg",
        title : "Nike T-shirt",
        dcost : 1120,
        ocost : 1860,
        reviews : 88,
    },
    {
        kid : 2,
        image : "./images/itemtwo.jpg",
        title : "Puma Essential T-Shirt",
        dcost : 520,
        ocost : 2000,
        reviews : 22,
    },
    {
        kid : 3,
        image : "./images/itemthree.jpg",
        title : "Lululemon Swiftly Tech T-Shirt",
        dcost : 600,
        ocost : 1200,
        reviews : 67,
    },
    {
        kid : 4,
        image : "./images/itemfour.jpg",
        title : "Columbia Terminal Tackle Shirt",
        dcost : 390,
        ocost : 1499,
        reviews : 55,
    },
    {
        kid : 1,
        image : "./images/itemone.jpg",
        title : "Nike T-shirt",
        dcost : 1120,
        ocost : 1860,
        reviews : 88,
    },
    {
        kid : 2,
        image : "./images/itemtwo.jpg",
        title : "Puma Essential T-Shirt",
        dcost : 520,
        ocost : 2000,
        reviews : 22,
    },
    {
        kid : 3,
        image : "./images/itemthree.jpg",
        title : "Lululemon Swiftly Tech T-Shirt",
        dcost : 600,
        ocost : 1200,
        reviews : 67,
    },
    {
        kid : 4,
        image : "./images/itemfour.jpg",
        title : "Columbia Terminal Tackle Shirt",
        dcost : 390,
        ocost : 1499,
        reviews : 55,
    },
    {
        kid : 1,
        image : "./images/itemone.jpg",
        title : "Nike T-shirt",
        dcost : 1120,
        ocost : 1860,
        reviews : 88,
    },
    {
        kid : 2,
        image : "./images/itemtwo.jpg",
        title : "Puma Essential T-Shirt",
        dcost : 520,
        ocost : 2000,
        reviews : 22,
    },
    {
        kid : 3,
        image : "./images/itemthree.jpg",
        title : "Lululemon Swiftly Tech T-Shirt",
        dcost : 600,
        ocost : 1200,
        reviews : 67,
    },
    {
        kid : 4,
        image : "./images/itemfour.jpg",
        title : "Columbia Terminal Tackle Shirt",
        dcost : 390,
        ocost : 1499,
        reviews : 55,
    },
    
]